name: Documents utiles

# Name of the author
author: Marie Zufferey

# Short bio or description (displayed in the header)
description: documents utiles pour l'OPDir


url:  https://sca-opdir.github.io/ # http://www.amitmerchant.com/reverie
enforce_ssl:  https://sca-opdir.github.io/ # https://www.amitmerchant.com/reverie
baseurl: '/documents-utiles/'
permalink: pretty
title: 'Jekyll Serif'

logo:
  mobile: "images/logo/logo-mobile.svg"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/logo.svg"
  desktop_height: "32px"
  desktop_width: "120px"

home: 
  limit_services: 6

collections:
  services:
    output: true
    sort_by: weight
    permalink: /services/:name/
  team:
    output: true

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sass-converter

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
  
  
